// Generated by Bisonc++ V2.09.03 on Tue, 11 Feb 2014 00:00:26 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {275, 4}, // 1: program ->  declaration_statement_list procedure_name #0001 procedure_body
     {279, 0}, // 2: #0001 ->  <empty>
     {275, 3}, // 3: program ->  procedure_name #0002 procedure_body
     {280, 0}, // 4: #0002 ->  <empty>
     {277, 3}, // 5: procedure_name (NAME) ->  NAME '(' ')'
     {278, 5}, // 6: procedure_body ('{') ->  '{' declaration_statement_list #0003 basic_block_list '}'
     {282, 0}, // 7: #0003 ->  <empty>
     {278, 3}, // 8: procedure_body ('{') ->  '{' basic_block_list '}'
     {276, 1}, // 9: declaration_statement_list ->  declaration_statement
     {276, 2}, // 10: declaration_statement_list ->  declaration_statement_list declaration_statement
     {283, 3}, // 11: declaration_statement (INTEGER) ->  INTEGER NAME ';'
     {283, 3}, // 12: declaration_statement (FLOAT) ->  FLOAT NAME ';'
     {283, 3}, // 13: declaration_statement (DOUBLE) ->  DOUBLE NAME ';'
     {281, 2}, // 14: basic_block_list ->  basic_block_list basic_block
     {281, 1}, // 15: basic_block_list ->  basic_block
     {284, 3}, // 16: basic_block (BB) ->  BB ':' executable_statement_list
     {286, 10}, // 17: if_else_clause (IF) ->  IF '(' relop_expression ')' GOTO BB ';' ELSE GOTO BB
     {287, 3}, // 18: relop_expression (LT) ->  relop_expression LT relop_expression
     {287, 3}, // 19: relop_expression (LE) ->  relop_expression LE relop_expression
     {287, 3}, // 20: relop_expression (GT) ->  relop_expression GT relop_expression
     {287, 3}, // 21: relop_expression (GE) ->  relop_expression GE relop_expression
     {287, 3}, // 22: relop_expression (EQ) ->  relop_expression EQ relop_expression
     {287, 3}, // 23: relop_expression (NE) ->  relop_expression NE relop_expression
     {287, 1}, // 24: relop_expression ->  arith_expression
     {289, 1}, // 25: arithop ('+') ->  '+'
     {289, 1}, // 26: arithop ('-') ->  '-'
     {289, 1}, // 27: arithop ('*') ->  '*'
     {289, 1}, // 28: arithop ('/') ->  '/'
     {290, 4}, // 29: typecast_exp ('(') ->  '(' FLOAT ')' relop_expression
     {290, 4}, // 30: typecast_exp ('(') ->  '(' DOUBLE ')' relop_expression
     {290, 4}, // 31: typecast_exp ('(') ->  '(' INTEGER ')' relop_expression
     {288, 1}, // 32: arith_expression ->  variable
     {288, 1}, // 33: arith_expression ->  constant
     {288, 1}, // 34: arith_expression ->  typecast_exp
     {288, 3}, // 35: arith_expression ('(') ->  '(' arith_expression ')'
     {288, 3}, // 36: arith_expression ->  variable arithop arith_expression
     {288, 3}, // 37: arith_expression ->  constant arithop arith_expression
     {285, 1}, // 38: executable_statement_list ->  assignment_statement_list
     {285, 3}, // 39: executable_statement_list (RETURN) ->  assignment_statement_list RETURN ';'
     {285, 4}, // 40: executable_statement_list (GOTO) ->  assignment_statement_list GOTO BB ';'
     {285, 3}, // 41: executable_statement_list (';') ->  assignment_statement_list if_else_clause ';'
     {293, 0}, // 42: assignment_statement_list ->  <empty>
     {293, 2}, // 43: assignment_statement_list ->  assignment_statement_list assignment_statement
     {294, 4}, // 44: assignment_statement (ASSIGN_OP) ->  variable ASSIGN_OP relop_expression ';'
     {291, 1}, // 45: variable (NAME) ->  NAME
     {291, 2}, // 46: variable ('-') ->  '-' NAME
     {292, 1}, // 47: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {292, 1}, // 48: constant (FLOAT_NUMBER) ->  FLOAT_NUMBER
     {295, 1}, // 49: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 9} },                              
    { {       275}, { 1} }, // program                   
    { {       276}, { 2} }, // declaration_statement_list
    { {       277}, { 3} }, // procedure_name            
    { {       283}, { 4} }, // declaration_statement     
    { {       260}, { 5} }, // NAME                      
    { {       262}, { 6} }, // INTEGER                   
    { {       263}, { 7} }, // FLOAT                     
    { {       264}, { 8} }, // DOUBLE                    
    { {         0}, { 0} },                              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, {  7} },                         
    { {       277}, {  9} }, // procedure_name       
    { {       283}, { 10} }, // declaration_statement
    { {       260}, {  5} }, // NAME                 
    { {       262}, {  6} }, // INTEGER              
    { {       263}, {  7} }, // FLOAT                
    { {       264}, {  8} }, // DOUBLE               
    { {         0}, {  0} },                         
};

SR__ s_3[] =
{
    { { DEF_RED}, {  2} },         
    { {     280}, { 11} }, // #0002
    { {       0}, { -4} },         
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 12} }, // '('
    { {         0}, {  0} },       
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 13} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 14} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 15} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_9[] =
{
    { { DEF_RED}, {  2} },         
    { {     279}, { 16} }, // #0001
    { {       0}, { -2} },         
};

SR__ s_10[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       278}, { 17} }, // procedure_body
    { {       123}, { 18} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 19} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 20} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 21} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 22} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       278}, { 23} }, // procedure_body
    { {       123}, { 18} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_17[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  9} },                              
    { {       276}, { 24} }, // declaration_statement_list
    { {       281}, { 25} }, // basic_block_list          
    { {       283}, {  4} }, // declaration_statement     
    { {       284}, { 26} }, // basic_block               
    { {       262}, {  6} }, // INTEGER                   
    { {       263}, {  7} }, // FLOAT                     
    { {       264}, {  8} }, // DOUBLE                    
    { {       258}, { 27} }, // BB                        
    { {         0}, {  0} },                              
};

SR__ s_19[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_24[] =
{
    { { REQ_DEF}, {  6} },                         
    { {     282}, { 28} }, // #0003                
    { {     283}, { 10} }, // declaration_statement
    { {     262}, {  6} }, // INTEGER              
    { {     263}, {  7} }, // FLOAT                
    { {     264}, {  8} }, // DOUBLE               
    { {       0}, { -7} },                         
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 29} }, // '}'        
    { {       284}, { 30} }, // basic_block
    { {       258}, { 27} }, // BB         
    { {         0}, {  0} },               
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        58}, { 31} }, // ':'
    { {         0}, {  0} },       
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       281}, { 32} }, // basic_block_list
    { {       284}, { 26} }, // basic_block     
    { {       258}, { 27} }, // BB              
    { {         0}, {  0} },                    
};

SR__ s_29[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   3} },                             
    { {     285}, {  33} }, // executable_statement_list
    { {     293}, {  34} }, // assignment_statement_list
    { {       0}, { -42} },                             
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 35} }, // '}'        
    { {       284}, { 30} }, // basic_block
    { {       258}, { 27} }, // BB         
    { {         0}, {  0} },               
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_34[] =
{
    { { REQ_DEF}, {   9} },                        
    { {     261}, {  36} }, // RETURN              
    { {     267}, {  37} }, // GOTO                
    { {     286}, {  38} }, // if_else_clause      
    { {     294}, {  39} }, // assignment_statement
    { {     265}, {  40} }, // IF                  
    { {     291}, {  41} }, // variable            
    { {     260}, {  42} }, // NAME                
    { {      45}, {  43} }, // '-'                 
    { {       0}, { -38} },                        
};

SR__ s_35[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 44} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       258}, { 45} }, // BB
    { {         0}, {  0} },      
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 46} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 47} }, // '('
    { {         0}, {  0} },       
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       268}, { 48} }, // ASSIGN_OP
    { {         0}, {  0} },             
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 49} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 50} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 11} },                    
    { {       287}, { 51} }, // relop_expression
    { {       288}, { 52} }, // arith_expression
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, { 11} },                    
    { {       287}, { 59} }, // relop_expression
    { {       288}, { 52} }, // arith_expression
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  8} },       
    { {        41}, { 60} }, // ')'
    { {       271}, { 61} }, // LT 
    { {       272}, { 62} }, // LE 
    { {       273}, { 63} }, // GT 
    { {       274}, { 64} }, // GE 
    { {       270}, { 65} }, // EQ 
    { {       269}, { 66} }, // NE 
    { {         0}, {  0} },       
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_53[] =
{
    { { REQ_DEF}, {   6} },           
    { {     289}, {  67} }, // arithop
    { {      43}, {  68} }, // '+'    
    { {      45}, {  69} }, // '-'    
    { {      42}, {  70} }, // '*'    
    { {      47}, {  71} }, // '/'    
    { {       0}, { -32} },           
};

SR__ s_54[] =
{
    { { REQ_DEF}, {   6} },           
    { {     289}, {  72} }, // arithop
    { {      43}, {  68} }, // '+'    
    { {      45}, {  69} }, // '-'    
    { {      42}, {  70} }, // '*'    
    { {      47}, {  71} }, // '/'    
    { {       0}, { -33} },           
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       288}, { 73} }, // arith_expression
    { {       263}, { 74} }, // FLOAT           
    { {       264}, { 75} }, // DOUBLE          
    { {       262}, { 76} }, // INTEGER         
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  8} },       
    { {        59}, { 77} }, // ';'
    { {       271}, { 61} }, // LT 
    { {       272}, { 62} }, // LE 
    { {       273}, { 63} }, // GT 
    { {       274}, { 64} }, // GE 
    { {       270}, { 65} }, // EQ 
    { {       269}, { 66} }, // NE 
    { {         0}, {  0} },       
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       267}, { 78} }, // GOTO
    { {         0}, {  0} },        
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, { 11} },                    
    { {       287}, { 79} }, // relop_expression
    { {       288}, { 52} }, // arith_expression
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, { 11} },                    
    { {       287}, { 80} }, // relop_expression
    { {       288}, { 52} }, // arith_expression
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, { 11} },                    
    { {       287}, { 81} }, // relop_expression
    { {       288}, { 52} }, // arith_expression
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, { 11} },                    
    { {       287}, { 82} }, // relop_expression
    { {       288}, { 52} }, // arith_expression
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, { 11} },                    
    { {       287}, { 83} }, // relop_expression
    { {       288}, { 52} }, // arith_expression
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, { 11} },                    
    { {       287}, { 84} }, // relop_expression
    { {       288}, { 52} }, // arith_expression
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       288}, { 85} }, // arith_expression
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       288}, { 86} }, // arith_expression
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 87} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 88} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 89} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 90} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       258}, { 91} }, // BB
    { {         0}, {  0} },      
};

SR__ s_79[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_80[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_81[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_82[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_83[] =
{
    { { REQ_DEF}, {   5} },      
    { {     271}, {  61} }, // LT
    { {     272}, {  62} }, // LE
    { {     273}, {  63} }, // GT
    { {     274}, {  64} }, // GE
    { {       0}, { -22} },      
};

SR__ s_84[] =
{
    { { REQ_DEF}, {   5} },      
    { {     271}, {  61} }, // LT
    { {     272}, {  62} }, // LE
    { {     273}, {  63} }, // GT
    { {     274}, {  64} }, // GE
    { {       0}, { -23} },      
};

SR__ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, { 11} },                    
    { {       287}, { 92} }, // relop_expression
    { {       288}, { 52} }, // arith_expression
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, { 11} },                    
    { {       287}, { 93} }, // relop_expression
    { {       288}, { 52} }, // arith_expression
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, { 11} },                    
    { {       287}, { 94} }, // relop_expression
    { {       288}, { 52} }, // arith_expression
    { {       291}, { 53} }, // variable        
    { {       292}, { 54} }, // constant        
    { {       290}, { 55} }, // typecast_exp    
    { {        40}, { 56} }, // '('             
    { {       260}, { 42} }, // NAME            
    { {        45}, { 43} }, // '-'             
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 95} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_92[] =
{
    { { REQ_DEF}, {   7} },      
    { {     271}, {  61} }, // LT
    { {     272}, {  62} }, // LE
    { {     273}, {  63} }, // GT
    { {     274}, {  64} }, // GE
    { {     270}, {  65} }, // EQ
    { {     269}, {  66} }, // NE
    { {       0}, { -29} },      
};

SR__ s_93[] =
{
    { { REQ_DEF}, {   7} },      
    { {     271}, {  61} }, // LT
    { {     272}, {  62} }, // LE
    { {     273}, {  63} }, // GT
    { {     274}, {  64} }, // GE
    { {     270}, {  65} }, // EQ
    { {     269}, {  66} }, // NE
    { {       0}, { -30} },      
};

SR__ s_94[] =
{
    { { REQ_DEF}, {   7} },      
    { {     271}, {  61} }, // LT
    { {     272}, {  62} }, // LE
    { {     273}, {  63} }, // GT
    { {     274}, {  64} }, // GE
    { {     270}, {  65} }, // EQ
    { {     269}, {  66} }, // NE
    { {       0}, { -31} },      
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       266}, { 96} }, // ELSE
    { {         0}, {  0} },        
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       267}, { 97} }, // GOTO
    { {         0}, {  0} },        
};

SR__ s_97[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       258}, { 98} }, // BB
    { {         0}, {  0} },      
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
        { 
        
         }
        break;

        case 2:
        d_val__ = d_vsp__[-1];
        { 
         
        
         }
        break;

        case 3:
        { 
        
         }
        break;

        case 4:
        d_val__ = d_vsp__[0];
        { 
        
         }
        break;

        case 5:
        { 
        
         }
        break;

        case 6:
        { 
        
         }
        break;

        case 7:
        d_val__ = d_vsp__[-1];
        { 
        
         }
        break;

        case 8:
        { 
        
         }
        break;

        case 9:
        { 
        
         }
        break;

        case 10:
        { 
        
         }
        break;

        case 11:
        { 
        
         }
        break;

        case 12:
        {
         }
        break;

        case 13:
        {
         }
        break;

        case 14:
        { 
        
         }
        break;

        case 15:
        { 
        
         }
        break;

        case 16:
        { 
        
         }
        break;

        case 17:
        { 
        
         }
        break;

        case 18:
        { 
        
         }
        break;

        case 19:
        { 
        
         }
        break;

        case 20:
        { 
        
         }
        break;

        case 21:
        { 
        
         }
        break;

        case 22:
        { 
        
         }
        break;

        case 23:
        { 
        
         }
        break;

        case 24:
        {
         }
        break;

        case 25:
        {
         }
        break;

        case 26:
        {
         }
        break;

        case 27:
        {
         }
        break;

        case 28:
        {
         }
        break;

        case 29:
        {
         }
        break;

        case 30:
        {
         }
        break;

        case 31:
        {
         }
        break;

        case 32:
        { 
        
         }
        break;

        case 33:
        { 
        
         }
        break;

        case 34:
        {
         }
        break;

        case 35:
        {
         }
        break;

        case 36:
        {
         }
        break;

        case 37:
        {
         }
        break;

        case 38:
        { 
        
         }
        break;

        case 39:
        { 
        
         }
        break;

        case 40:
        { 
        
         }
        break;

        case 41:
        { 
        
         }
        break;

        case 42:
        { 
        
         }
        break;

        case 43:
        { 
        
         }
        break;

        case 44:
        { 
        
         }
        break;

        case 45:
        { 
        
         }
        break;

        case 46:
        {
         
         }
        break;

        case 47:
        { 
        
         }
        break;

        case 48:
        {
         }
        break;

    }
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

