// Generated by Bisonc++ V2.09.03 on Mon, 03 Mar 2014 19:31:26 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {276, 4}, // 1: program ->  declaration_statement_list procedure_name #0001 procedure_body
     {280, 0}, // 2: #0001 ->  <empty>
     {276, 3}, // 3: program ->  procedure_name #0002 procedure_body
     {281, 0}, // 4: #0002 ->  <empty>
     {276, 4}, // 5: program ->  program procedure_name #0003 procedure_body
     {282, 0}, // 6: #0003 ->  <empty>
     {278, 3}, // 7: procedure_name (NAME) ->  NAME '(' ')'
     {278, 4}, // 8: procedure_name (NAME) ->  NAME '(' parameter_list ')'
     {279, 5}, // 9: procedure_body ('{') ->  '{' declaration_statement_list #0004 basic_block_list '}'
     {285, 0}, // 10: #0004 ->  <empty>
     {279, 3}, // 11: procedure_body ('{') ->  '{' basic_block_list '}'
     {277, 1}, // 12: declaration_statement_list ->  declaration_statement
     {277, 2}, // 13: declaration_statement_list ->  declaration_statement_list declaration_statement
     {286, 3}, // 14: declaration_statement (INTEGER) ->  INTEGER NAME ';'
     {286, 3}, // 15: declaration_statement (FLOAT) ->  FLOAT NAME ';'
     {286, 3}, // 16: declaration_statement (DOUBLE) ->  DOUBLE NAME ';'
     {286, 3}, // 17: declaration_statement (';') ->  returnType procedure_name ';'
     {283, 1}, // 18: parameter_list ->  parameters
     {283, 3}, // 19: parameter_list (',') ->  parameter_list ',' parameters
     {288, 2}, // 20: parameters (INTEGER) ->  INTEGER NAME
     {288, 2}, // 21: parameters (FLOAT) ->  FLOAT NAME
     {288, 2}, // 22: parameters (DOUBLE) ->  DOUBLE NAME
     {288, 2}, // 23: parameters ->  returnType procedure_name
     {284, 2}, // 24: basic_block_list ->  basic_block_list basic_block
     {284, 1}, // 25: basic_block_list ->  basic_block
     {289, 3}, // 26: basic_block (BB) ->  BB ':' executable_statement_list
     {291, 10}, // 27: if_else_clause (IF) ->  IF '(' relop_expression ')' GOTO BB ';' ELSE GOTO BB
     {292, 1}, // 28: relop_expression ->  atomic
     {292, 1}, // 29: relop_expression ->  procedure_name
     {292, 3}, // 30: relop_expression (LT) ->  relop_expression LT relop_expression
     {292, 3}, // 31: relop_expression (LE) ->  relop_expression LE relop_expression
     {292, 3}, // 32: relop_expression (GT) ->  relop_expression GT relop_expression
     {292, 3}, // 33: relop_expression (GE) ->  relop_expression GE relop_expression
     {292, 3}, // 34: relop_expression (EQ) ->  relop_expression EQ relop_expression
     {292, 3}, // 35: relop_expression (NE) ->  relop_expression NE relop_expression
     {292, 3}, // 36: relop_expression ('+') ->  relop_expression '+' relop_expression
     {292, 3}, // 37: relop_expression ('-') ->  relop_expression '-' relop_expression
     {292, 3}, // 38: relop_expression ('*') ->  relop_expression '*' relop_expression
     {292, 3}, // 39: relop_expression ('/') ->  relop_expression '/' relop_expression
     {292, 1}, // 40: relop_expression ->  typecast_exp
     {292, 2}, // 41: relop_expression ('-') ->  '-' atomic
     {293, 1}, // 42: atomic ->  variable
     {293, 1}, // 43: atomic ->  constant
     {293, 3}, // 44: atomic ('(') ->  '(' relop_expression ')'
     {297, 1}, // 45: dataType (FLOAT) ->  FLOAT
     {297, 1}, // 46: dataType (DOUBLE) ->  DOUBLE
     {297, 1}, // 47: dataType (INTEGER) ->  INTEGER
     {287, 1}, // 48: returnType (INTEGER) ->  INTEGER
     {287, 1}, // 49: returnType (FLOAT) ->  FLOAT
     {287, 1}, // 50: returnType (VOID) ->  VOID
     {287, 1}, // 51: returnType (DOUBLE) ->  DOUBLE
     {294, 4}, // 52: typecast_exp ('(') ->  '(' dataType ')' atomic
     {290, 1}, // 53: executable_statement_list ->  assignment_statement_list
     {290, 3}, // 54: executable_statement_list (RETURN) ->  assignment_statement_list RETURN ';'
     {290, 4}, // 55: executable_statement_list (RETURN) ->  assignment_statement_list RETURN relop_expression ';'
     {290, 4}, // 56: executable_statement_list (GOTO) ->  assignment_statement_list GOTO BB ';'
     {290, 3}, // 57: executable_statement_list (';') ->  assignment_statement_list if_else_clause ';'
     {298, 0}, // 58: assignment_statement_list ->  <empty>
     {298, 2}, // 59: assignment_statement_list ->  assignment_statement_list assignment_statement
     {299, 4}, // 60: assignment_statement (ASSIGN_OP) ->  variable ASSIGN_OP relop_expression ';'
     {299, 2}, // 61: assignment_statement (';') ->  procedure_name ';'
     {295, 1}, // 62: variable (NAME) ->  NAME
     {296, 1}, // 63: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {296, 1}, // 64: constant (FLOAT_NUMBER) ->  FLOAT_NUMBER
     {300, 1}, // 65: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 11} },                              
    { {       276}, {  1} }, // program                   
    { {       277}, {  2} }, // declaration_statement_list
    { {       278}, {  3} }, // procedure_name            
    { {       286}, {  4} }, // declaration_statement     
    { {       260}, {  5} }, // NAME                      
    { {       262}, {  6} }, // INTEGER                   
    { {       263}, {  7} }, // FLOAT                     
    { {       264}, {  8} }, // DOUBLE                    
    { {       287}, {  9} }, // returnType                
    { {       265}, { 10} }, // VOID                      
    { {         0}, {  0} },                              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            4} },                  
    { {       278}, {           11} }, // procedure_name
    { {       260}, {            5} }, // NAME          
    { {     _EOF_}, { PARSE_ACCEPT} },                  
    { {         0}, {            0} },                  
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, {  9} },                         
    { {       278}, { 12} }, // procedure_name       
    { {       286}, { 13} }, // declaration_statement
    { {       260}, {  5} }, // NAME                 
    { {       262}, {  6} }, // INTEGER              
    { {       263}, {  7} }, // FLOAT                
    { {       264}, {  8} }, // DOUBLE               
    { {       287}, {  9} }, // returnType           
    { {       265}, { 10} }, // VOID                 
    { {         0}, {  0} },                         
};

SR__ s_3[] =
{
    { { DEF_RED}, {  2} },         
    { {     281}, { 14} }, // #0002
    { {       0}, { -4} },         
};

SR__ s_4[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 15} }, // '('
    { {         0}, {  0} },       
};

SR__ s_6[] =
{
    { { REQ_DEF}, {   2} },        
    { {     260}, {  16} }, // NAME
    { {       0}, { -48} },        
};

SR__ s_7[] =
{
    { { REQ_DEF}, {   2} },        
    { {     260}, {  17} }, // NAME
    { {       0}, { -49} },        
};

SR__ s_8[] =
{
    { { REQ_DEF}, {   2} },        
    { {     260}, {  18} }, // NAME
    { {       0}, { -51} },        
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       278}, { 19} }, // procedure_name
    { {       260}, {  5} }, // NAME          
    { {         0}, {  0} },                  
};

SR__ s_10[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_11[] =
{
    { { DEF_RED}, {  2} },         
    { {     282}, { 20} }, // #0003
    { {       0}, { -6} },         
};

SR__ s_12[] =
{
    { { DEF_RED}, {  2} },         
    { {     280}, { 21} }, // #0001
    { {       0}, { -2} },         
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       279}, { 22} }, // procedure_body
    { {       123}, { 23} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  9} },                  
    { {        41}, { 24} }, // ')'           
    { {       283}, { 25} }, // parameter_list
    { {       288}, { 26} }, // parameters    
    { {       262}, { 27} }, // INTEGER       
    { {       263}, { 28} }, // FLOAT         
    { {       264}, { 29} }, // DOUBLE        
    { {       287}, { 30} }, // returnType    
    { {       265}, { 10} }, // VOID          
    { {         0}, {  0} },                  
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 31} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 32} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 33} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 34} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       279}, { 35} }, // procedure_body
    { {       123}, { 23} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       279}, { 36} }, // procedure_body
    { {       123}, { 23} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_22[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, { 11} },                              
    { {       277}, { 37} }, // declaration_statement_list
    { {       284}, { 38} }, // basic_block_list          
    { {       286}, {  4} }, // declaration_statement     
    { {       289}, { 39} }, // basic_block               
    { {       262}, {  6} }, // INTEGER                   
    { {       263}, {  7} }, // FLOAT                     
    { {       264}, {  8} }, // DOUBLE                    
    { {       287}, {  9} }, // returnType                
    { {       258}, { 40} }, // BB                        
    { {       265}, { 10} }, // VOID                      
    { {         0}, {  0} },                              
};

SR__ s_24[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 41} }, // ')'
    { {        44}, { 42} }, // ','
    { {         0}, {  0} },       
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_27[] =
{
    { { REQ_DEF}, {   2} },        
    { {     260}, {  43} }, // NAME
    { {       0}, { -48} },        
};

SR__ s_28[] =
{
    { { REQ_DEF}, {   2} },        
    { {     260}, {  44} }, // NAME
    { {       0}, { -49} },        
};

SR__ s_29[] =
{
    { { REQ_DEF}, {   2} },        
    { {     260}, {  45} }, // NAME
    { {       0}, { -51} },        
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       278}, { 46} }, // procedure_name
    { {       260}, {  5} }, // NAME          
    { {         0}, {  0} },                  
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_35[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_37[] =
{
    { { REQ_DEF}, {   8} },                         
    { {     285}, {  47} }, // #0004                
    { {     286}, {  13} }, // declaration_statement
    { {     262}, {   6} }, // INTEGER              
    { {     263}, {   7} }, // FLOAT                
    { {     264}, {   8} }, // DOUBLE               
    { {     287}, {   9} }, // returnType           
    { {     265}, {  10} }, // VOID                 
    { {       0}, { -10} },                         
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 48} }, // '}'        
    { {       289}, { 49} }, // basic_block
    { {       258}, { 40} }, // BB         
    { {         0}, {  0} },               
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        58}, { 50} }, // ':'
    { {         0}, {  0} },       
};

SR__ s_41[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  7} },              
    { {       288}, { 51} }, // parameters
    { {       262}, { 27} }, // INTEGER   
    { {       263}, { 28} }, // FLOAT     
    { {       264}, { 29} }, // DOUBLE    
    { {       287}, { 30} }, // returnType
    { {       265}, { 10} }, // VOID      
    { {         0}, {  0} },              
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       284}, { 52} }, // basic_block_list
    { {       289}, { 39} }, // basic_block     
    { {       258}, { 40} }, // BB              
    { {         0}, {  0} },                    
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {   3} },                             
    { {     290}, {  53} }, // executable_statement_list
    { {     298}, {  54} }, // assignment_statement_list
    { {       0}, { -58} },                             
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 55} }, // '}'        
    { {       289}, { 49} }, // basic_block
    { {       258}, { 40} }, // BB         
    { {         0}, {  0} },               
};

SR__ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_54[] =
{
    { { REQ_DEF}, {   9} },                        
    { {     261}, {  56} }, // RETURN              
    { {     268}, {  57} }, // GOTO                
    { {     291}, {  58} }, // if_else_clause      
    { {     299}, {  59} }, // assignment_statement
    { {     266}, {  60} }, // IF                  
    { {     295}, {  61} }, // variable            
    { {     278}, {  62} }, // procedure_name      
    { {     260}, {  63} }, // NAME                
    { {       0}, { -53} },                        
};

SR__ s_55[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {        59}, { 64} }, // ';'             
    { {       292}, { 65} }, // relop_expression
    { {       293}, { 66} }, // atomic          
    { {       278}, { 67} }, // procedure_name  
    { {       294}, { 68} }, // typecast_exp    
    { {        45}, { 69} }, // '-'             
    { {       295}, { 70} }, // variable        
    { {       296}, { 71} }, // constant        
    { {        40}, { 72} }, // '('             
    { {       260}, { 63} }, // NAME            
    { {       257}, { 73} }, // INTEGER_NUMBER  
    { {       259}, { 74} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       258}, { 75} }, // BB
    { {         0}, {  0} },      
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 76} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 77} }, // '('
    { {         0}, {  0} },       
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       269}, { 78} }, // ASSIGN_OP
    { {         0}, {  0} },             
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 79} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_63[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, {  15} }, // '('
    { {       0}, { -62} },       
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, { 12} },       
    { {        59}, { 80} }, // ';'
    { {       272}, { 81} }, // LT 
    { {       273}, { 82} }, // LE 
    { {       274}, { 83} }, // GT 
    { {       275}, { 84} }, // GE 
    { {       271}, { 85} }, // EQ 
    { {       270}, { 86} }, // NE 
    { {        43}, { 87} }, // '+'
    { {        45}, { 88} }, // '-'
    { {        42}, { 89} }, // '*'
    { {        47}, { 90} }, // '/'
    { {         0}, {  0} },       
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  8} },                  
    { {       293}, { 91} }, // atomic        
    { {       295}, { 70} }, // variable      
    { {       296}, { 71} }, // constant      
    { {        40}, { 92} }, // '('           
    { {       260}, { 93} }, // NAME          
    { {       257}, { 73} }, // INTEGER_NUMBER
    { {       259}, { 74} }, // FLOAT_NUMBER  
    { {         0}, {  0} },                  
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, { 16} },                    
    { {       292}, { 94} }, // relop_expression
    { {       297}, { 95} }, // dataType        
    { {       293}, { 66} }, // atomic          
    { {       278}, { 67} }, // procedure_name  
    { {       294}, { 68} }, // typecast_exp    
    { {        45}, { 69} }, // '-'             
    { {       263}, { 96} }, // FLOAT           
    { {       264}, { 97} }, // DOUBLE          
    { {       262}, { 98} }, // INTEGER         
    { {       295}, { 70} }, // variable        
    { {       296}, { 71} }, // constant        
    { {        40}, { 72} }, // '('             
    { {       260}, { 63} }, // NAME            
    { {       257}, { 73} }, // INTEGER_NUMBER  
    { {       259}, { 74} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -64} }, 
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 99} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  12} },                    
    { {       292}, { 100} }, // relop_expression
    { {       293}, {  66} }, // atomic          
    { {       278}, {  67} }, // procedure_name  
    { {       294}, {  68} }, // typecast_exp    
    { {        45}, {  69} }, // '-'             
    { {       295}, {  70} }, // variable        
    { {       296}, {  71} }, // constant        
    { {        40}, {  72} }, // '('             
    { {       260}, {  63} }, // NAME            
    { {       257}, {  73} }, // INTEGER_NUMBER  
    { {       259}, {  74} }, // FLOAT_NUMBER    
    { {         0}, {   0} },                    
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  12} },                    
    { {       292}, { 101} }, // relop_expression
    { {       293}, {  66} }, // atomic          
    { {       278}, {  67} }, // procedure_name  
    { {       294}, {  68} }, // typecast_exp    
    { {        45}, {  69} }, // '-'             
    { {       295}, {  70} }, // variable        
    { {       296}, {  71} }, // constant        
    { {        40}, {  72} }, // '('             
    { {       260}, {  63} }, // NAME            
    { {       257}, {  73} }, // INTEGER_NUMBER  
    { {       259}, {  74} }, // FLOAT_NUMBER    
    { {         0}, {   0} },                    
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  12} },                    
    { {       292}, { 102} }, // relop_expression
    { {       293}, {  66} }, // atomic          
    { {       278}, {  67} }, // procedure_name  
    { {       294}, {  68} }, // typecast_exp    
    { {        45}, {  69} }, // '-'             
    { {       295}, {  70} }, // variable        
    { {       296}, {  71} }, // constant        
    { {        40}, {  72} }, // '('             
    { {       260}, {  63} }, // NAME            
    { {       257}, {  73} }, // INTEGER_NUMBER  
    { {       259}, {  74} }, // FLOAT_NUMBER    
    { {         0}, {   0} },                    
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  12} },                    
    { {       292}, { 103} }, // relop_expression
    { {       293}, {  66} }, // atomic          
    { {       278}, {  67} }, // procedure_name  
    { {       294}, {  68} }, // typecast_exp    
    { {        45}, {  69} }, // '-'             
    { {       295}, {  70} }, // variable        
    { {       296}, {  71} }, // constant        
    { {        40}, {  72} }, // '('             
    { {       260}, {  63} }, // NAME            
    { {       257}, {  73} }, // INTEGER_NUMBER  
    { {       259}, {  74} }, // FLOAT_NUMBER    
    { {         0}, {   0} },                    
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  12} },                    
    { {       292}, { 104} }, // relop_expression
    { {       293}, {  66} }, // atomic          
    { {       278}, {  67} }, // procedure_name  
    { {       294}, {  68} }, // typecast_exp    
    { {        45}, {  69} }, // '-'             
    { {       295}, {  70} }, // variable        
    { {       296}, {  71} }, // constant        
    { {        40}, {  72} }, // '('             
    { {       260}, {  63} }, // NAME            
    { {       257}, {  73} }, // INTEGER_NUMBER  
    { {       259}, {  74} }, // FLOAT_NUMBER    
    { {         0}, {   0} },                    
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, {  12} },                    
    { {       292}, { 105} }, // relop_expression
    { {       293}, {  66} }, // atomic          
    { {       278}, {  67} }, // procedure_name  
    { {       294}, {  68} }, // typecast_exp    
    { {        45}, {  69} }, // '-'             
    { {       295}, {  70} }, // variable        
    { {       296}, {  71} }, // constant        
    { {        40}, {  72} }, // '('             
    { {       260}, {  63} }, // NAME            
    { {       257}, {  73} }, // INTEGER_NUMBER  
    { {       259}, {  74} }, // FLOAT_NUMBER    
    { {         0}, {   0} },                    
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  12} },                    
    { {       292}, { 106} }, // relop_expression
    { {       293}, {  66} }, // atomic          
    { {       278}, {  67} }, // procedure_name  
    { {       294}, {  68} }, // typecast_exp    
    { {        45}, {  69} }, // '-'             
    { {       295}, {  70} }, // variable        
    { {       296}, {  71} }, // constant        
    { {        40}, {  72} }, // '('             
    { {       260}, {  63} }, // NAME            
    { {       257}, {  73} }, // INTEGER_NUMBER  
    { {       259}, {  74} }, // FLOAT_NUMBER    
    { {         0}, {   0} },                    
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {  12} },                    
    { {       292}, { 107} }, // relop_expression
    { {       293}, {  66} }, // atomic          
    { {       278}, {  67} }, // procedure_name  
    { {       294}, {  68} }, // typecast_exp    
    { {        45}, {  69} }, // '-'             
    { {       295}, {  70} }, // variable        
    { {       296}, {  71} }, // constant        
    { {        40}, {  72} }, // '('             
    { {       260}, {  63} }, // NAME            
    { {       257}, {  73} }, // INTEGER_NUMBER  
    { {       259}, {  74} }, // FLOAT_NUMBER    
    { {         0}, {   0} },                    
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  12} },                    
    { {       292}, { 108} }, // relop_expression
    { {       293}, {  66} }, // atomic          
    { {       278}, {  67} }, // procedure_name  
    { {       294}, {  68} }, // typecast_exp    
    { {        45}, {  69} }, // '-'             
    { {       295}, {  70} }, // variable        
    { {       296}, {  71} }, // constant        
    { {        40}, {  72} }, // '('             
    { {       260}, {  63} }, // NAME            
    { {       257}, {  73} }, // INTEGER_NUMBER  
    { {       259}, {  74} }, // FLOAT_NUMBER    
    { {         0}, {   0} },                    
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {  12} },                    
    { {       292}, { 109} }, // relop_expression
    { {       293}, {  66} }, // atomic          
    { {       278}, {  67} }, // procedure_name  
    { {       294}, {  68} }, // typecast_exp    
    { {        45}, {  69} }, // '-'             
    { {       295}, {  70} }, // variable        
    { {       296}, {  71} }, // constant        
    { {        40}, {  72} }, // '('             
    { {       260}, {  63} }, // NAME            
    { {       257}, {  73} }, // INTEGER_NUMBER  
    { {       259}, {  74} }, // FLOAT_NUMBER    
    { {         0}, {   0} },                    
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {  12} },                    
    { {       292}, { 110} }, // relop_expression
    { {       293}, {  66} }, // atomic          
    { {       278}, {  67} }, // procedure_name  
    { {       294}, {  68} }, // typecast_exp    
    { {        45}, {  69} }, // '-'             
    { {       295}, {  70} }, // variable        
    { {       296}, {  71} }, // constant        
    { {        40}, {  72} }, // '('             
    { {       260}, {  63} }, // NAME            
    { {       257}, {  73} }, // INTEGER_NUMBER  
    { {       259}, {  74} }, // FLOAT_NUMBER    
    { {         0}, {   0} },                    
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {  12} },                    
    { {       292}, { 111} }, // relop_expression
    { {       293}, {  66} }, // atomic          
    { {       278}, {  67} }, // procedure_name  
    { {       294}, {  68} }, // typecast_exp    
    { {        45}, {  69} }, // '-'             
    { {       295}, {  70} }, // variable        
    { {       296}, {  71} }, // constant        
    { {        40}, {  72} }, // '('             
    { {       260}, {  63} }, // NAME            
    { {       257}, {  73} }, // INTEGER_NUMBER  
    { {       259}, {  74} }, // FLOAT_NUMBER    
    { {         0}, {   0} },                    
};

SR__ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, { 12} },                    
    { {       292}, { 94} }, // relop_expression
    { {       293}, { 66} }, // atomic          
    { {       278}, { 67} }, // procedure_name  
    { {       294}, { 68} }, // typecast_exp    
    { {        45}, { 69} }, // '-'             
    { {       295}, { 70} }, // variable        
    { {       296}, { 71} }, // constant        
    { {        40}, { 72} }, // '('             
    { {       260}, { 63} }, // NAME            
    { {       257}, { 73} }, // INTEGER_NUMBER  
    { {       259}, { 74} }, // FLOAT_NUMBER    
    { {         0}, {  0} },                    
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -62} }, 
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {  12} },       
    { {        41}, { 112} }, // ')'
    { {       272}, {  81} }, // LT 
    { {       273}, {  82} }, // LE 
    { {       274}, {  83} }, // GT 
    { {       275}, {  84} }, // GE 
    { {       271}, {  85} }, // EQ 
    { {       270}, {  86} }, // NE 
    { {        43}, {  87} }, // '+'
    { {        45}, {  88} }, // '-'
    { {        42}, {  89} }, // '*'
    { {        47}, {  90} }, // '/'
    { {         0}, {   0} },       
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 113} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_99[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {  12} },       
    { {        41}, { 114} }, // ')'
    { {       272}, {  81} }, // LT 
    { {       273}, {  82} }, // LE 
    { {       274}, {  83} }, // GT 
    { {       275}, {  84} }, // GE 
    { {       271}, {  85} }, // EQ 
    { {       270}, {  86} }, // NE 
    { {        43}, {  87} }, // '+'
    { {        45}, {  88} }, // '-'
    { {        42}, {  89} }, // '*'
    { {        47}, {  90} }, // '/'
    { {         0}, {   0} },       
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {  12} },       
    { {        59}, { 115} }, // ';'
    { {       272}, {  81} }, // LT 
    { {       273}, {  82} }, // LE 
    { {       274}, {  83} }, // GT 
    { {       275}, {  84} }, // GE 
    { {       271}, {  85} }, // EQ 
    { {       270}, {  86} }, // NE 
    { {        43}, {  87} }, // '+'
    { {        45}, {  88} }, // '-'
    { {        42}, {  89} }, // '*'
    { {        47}, {  90} }, // '/'
    { {         0}, {   0} },       
};

SR__ s_102[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  87} }, // '+'
    { {      45}, {  88} }, // '-'
    { {      42}, {  89} }, // '*'
    { {      47}, {  90} }, // '/'
    { {       0}, { -30} },       
};

SR__ s_103[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  87} }, // '+'
    { {      45}, {  88} }, // '-'
    { {      42}, {  89} }, // '*'
    { {      47}, {  90} }, // '/'
    { {       0}, { -31} },       
};

SR__ s_104[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  87} }, // '+'
    { {      45}, {  88} }, // '-'
    { {      42}, {  89} }, // '*'
    { {      47}, {  90} }, // '/'
    { {       0}, { -32} },       
};

SR__ s_105[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  87} }, // '+'
    { {      45}, {  88} }, // '-'
    { {      42}, {  89} }, // '*'
    { {      47}, {  90} }, // '/'
    { {       0}, { -33} },       
};

SR__ s_106[] =
{
    { { REQ_DEF}, {   9} },       
    { {     272}, {  81} }, // LT 
    { {     273}, {  82} }, // LE 
    { {     274}, {  83} }, // GT 
    { {     275}, {  84} }, // GE 
    { {      43}, {  87} }, // '+'
    { {      45}, {  88} }, // '-'
    { {      42}, {  89} }, // '*'
    { {      47}, {  90} }, // '/'
    { {       0}, { -34} },       
};

SR__ s_107[] =
{
    { { REQ_DEF}, {   9} },       
    { {     272}, {  81} }, // LT 
    { {     273}, {  82} }, // LE 
    { {     274}, {  83} }, // GT 
    { {     275}, {  84} }, // GE 
    { {      43}, {  87} }, // '+'
    { {      45}, {  88} }, // '-'
    { {      42}, {  89} }, // '*'
    { {      47}, {  90} }, // '/'
    { {       0}, { -35} },       
};

SR__ s_108[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  89} }, // '*'
    { {      47}, {  90} }, // '/'
    { {       0}, { -36} },       
};

SR__ s_109[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  89} }, // '*'
    { {      47}, {  90} }, // '/'
    { {       0}, { -37} },       
};

SR__ s_110[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_111[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_112[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {   8} },                  
    { {       293}, { 116} }, // atomic        
    { {       295}, {  70} }, // variable      
    { {       296}, {  71} }, // constant      
    { {        40}, {  92} }, // '('           
    { {       260}, {  93} }, // NAME          
    { {       257}, {  73} }, // INTEGER_NUMBER
    { {       259}, {  74} }, // FLOAT_NUMBER  
    { {         0}, {   0} },                  
};

SR__ s_114[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       268}, { 117} }, // GOTO
    { {         0}, {   0} },        
};

SR__ s_115[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_116[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_117[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       258}, { 118} }, // BB
    { {         0}, {   0} },      
};

SR__ s_118[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 119} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_119[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       267}, { 120} }, // ELSE
    { {         0}, {   0} },        
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       268}, { 121} }, // GOTO
    { {         0}, {   0} },        
};

SR__ s_121[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       258}, { 122} }, // BB
    { {         0}, {   0} },      
};

SR__ s_122[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
        { 
         
         
         }
        break;

        case 2:
        d_val__ = d_vsp__[-1];
        { 
         
         
         }
        break;

        case 3:
        {
         
         
         }
        break;

        case 4:
        d_val__ = d_vsp__[0];
        { 
         
         
         }
        break;

        case 5:
        {
         }
        break;

        case 6:
        d_val__ = d_vsp__[-1];
        {
         }
        break;

        case 7:
        {
        }
        break;

        case 8:
        {
         }
        break;

        case 9:
        { 
        
         }
        break;

        case 10:
        d_val__ = d_vsp__[-1];
        {
         
         }
        break;

        case 11:
        { 
        
         }
        break;

        case 12:
        { 
         
        
         }
        break;

        case 13:
        { 
        
         }
        break;

        case 14:
        { 
        
         }
        break;

        case 15:
        { 
        
         }
        break;

        case 16:
        {
         
        
         }
        break;

        case 17:
        { 
         cout<<"asdf\n"; 
         
        
         }
        break;

        case 18:
        {
         }
        break;

        case 19:
        {
         }
        break;

        case 20:
        { 
        
         }
        break;

        case 21:
        { 
        
         }
        break;

        case 22:
        {
         
        
         }
        break;

        case 23:
        { 
         
         
        
         }
        break;

        case 24:
        { 
         
        
         }
        break;

        case 25:
        { 
        
         }
        break;

        case 26:
        { 
         
         }
        break;

        case 27:
        { 
        
         }
        break;

        case 28:
        { 
        
         }
        break;

        case 29:
        {
         }
        break;

        case 30:
        { 
        
         }
        break;

        case 31:
        { 
        
         }
        break;

        case 32:
        { 
        
         }
        break;

        case 33:
        { 
        
         }
        break;

        case 34:
        { 
        
         }
        break;

        case 35:
        { 
        
         }
        break;

        case 36:
        { 
        
        
         }
        break;

        case 37:
        { 
        
         }
        break;

        case 38:
        { 
        
         }
        break;

        case 39:
        { 
        
         }
        break;

        case 40:
        { 
        
         }
        break;

        case 41:
        {
         
        
         }
        break;

        case 42:
        {
          
         }
        break;

        case 43:
        {
          
         }
        break;

        case 44:
        {
          
         }
        break;

        case 45:
        {
           
         }
        break;

        case 46:
        {
          
         }
        break;

        case 47:
        {
          
         }
        break;

        case 48:
        {
          
         }
        break;

        case 49:
        {
           
         }
        break;

        case 50:
        {
          
         }
        break;

        case 51:
        {
          
         }
        break;

        case 52:
        {
         
        
         
         }
        break;

        case 53:
        { 
          
         
         }
        break;

        case 54:
        { 
        
         
         }
        break;

        case 55:
        { 
        
         
         }
        break;

        case 56:
        { 
        
         }
        break;

        case 57:
        { 
         
        
         
         }
        break;

        case 58:
        { 
          
         
         }
        break;

        case 59:
        { 
        
         
         }
        break;

        case 60:
        { 
        
         
         }
        break;

        case 61:
        {
         }
        break;

        case 62:
        { 
        
         }
        break;

        case 63:
        { 
          
         
         }
        break;

        case 64:
        {
          
         }
        break;

    }
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

